name: Post welcome comment
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.10
        with:
          versionSpec: "6.0.0"

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.1.11
        with:
          updateAssemblyInfo: true

      - name: Display GitVersion variables (without prefix)
        run: |
          echo "FullSemVer (env.fullSemVer) : ${{ env.fullSemVer }}"

      - name: Display GitVersion variables (with prefix)
        run: |
          echo "FullSemVer (env.GitVersion_FullSemVer) : ${{ env.GitVersion_FullSemVer }}"

      - name: Display GitVersion outputs (step output without prefix)
        run: |
          echo "FullSemVer (steps.version_step.outputs.fullSemVer) : ${{ steps.version_step.outputs.fullSemVer }}"

      - name: Display GitVersion outputs (step output with prefix)
        run: |
          echo "FullSemVer (steps.version_step.outputs.GitVersion_FullSemVer) : ${{ steps.version_step.outputs.GitVersion_FullSemVer }}"

      - name: Output the formatted version
        uses: gittools/actions/gitversion/command@v3.1.11
        with:
          arguments: "/format {Major}.{Minor}" # any Output Variable can be used here


      # - name: Comment PR
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_URL: ${{ github.event.pull_request.html_url }}
      #   run: gh pr comment $PR_URL --body "Welcome to the repository!"
