name: Post welcome comment
on:
  pull_request:
    types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.10
        with:
          versionSpec: "6.0.0"

      - name: Comment PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment $PR_URL --body "Welcome to the repository!"
